export const RANDOM_JOKES = 'RANDOM_JOKES'
export const RANDOM_JOKES_START = 'RANDOM_JOKES_START'
export const RANDOM_JOKES_SUCCESS = 'RANDOM_JOKES_SUCCESS'
export const RANDOM_JOKES_ERROR = 'RANDOM_JOKES_ERROR'